# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x07\x61i_call\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\x07Request\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63hat_message\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"P\n\x08Response\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2=\n\tAIService\x12\x30\n\x07Process\x12\x10.ai_call.Request\x1a\x11.ai_call.Response\"\x00\x42\x0eZ\x0c.;ai_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014.;ai_service'
  _globals['_REQUEST']._serialized_start=62
  _globals['_REQUEST']._serialized_end=177
  _globals['_RESPONSE']._serialized_start=179
  _globals['_RESPONSE']._serialized_end=259
  _globals['_AISERVICE']._serialized_start=261
  _globals['_AISERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
